### ISSUE TITLE
this._findTabs is not a function

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [VizuaaLOG/microlib-tabs#10]
I have tried including your scripts like
```html
<script src="/bower_components/MicroLib-Utils/dist/utils.microlib-1.0.0.min.js"></script>
<script src="bower_components/microlib-tabs/dist/tabs.microlib-2.0.0.min.js"></script>
```
and like
```html
  <script src="/bower_components/microlib-tabs/dist/tabs-standalone.microlib-2.0.0.min.js"></script>
```
In both cases I still get the same error:

```console
tabs.microlib-2.0.0.min.js:1 Uncaught TypeError: this._findTabs is not a function
    at Object.MicroTabs [as Tabs] (tabs.microlib-2.0.0.min.js:1)
    at dashboard.html:86
MicroTabs @ tabs.microlib-2.0.0.min.js:1
(anonymous) @ dashboard.html:86
```

**Comment by VizuaaLOG** [comment]
This issue is partly related to your other issue #9. The readme is outdated, and so I will update this later today after work.

In order to initialise a new tabs instance please create a new one using the `new` keyword.
```javascript
new ML.Tabs(".tabs");
```

Also, the example markup is outdated as well. All classes are now prefixed, so the updated markup would be:
```html
<div class="tabs">
        <div class="microlib_tabs_tab" data-title="Tab 1">
            <h1>Tab 1</h1>
        </div>

        <div class="microlib_tabs_tab" data-title="Tab 2">
            <h1>Tab 2</h1>
        </div>

        <div class="microlib_tabs_tab" data-title="Tab 3">
            <h1>Tab 3</h1>
        </div>

        <div class="microlib_tabs_tab" data-title="Tab 4">
            <h1>Tab 4</h1>
        </div>
    </div>
```

This was changed to prevent collisions with other libraries. Although the updates to the readme were missed during the release.

Please let me know how you get on with the above.

**Comment by VizuaaLOG** [comment]
@BebeSparkelSparkel The documentation inconsistencies I believe have now been fixed.

I have also updated the library to `2.1.0` adding the ability for the classes to be customised via an optional object as the second argument. All of this has been added to the readme.

**Comment by BebeSparkelSparkel** [comment]
Thanks a lot!
